export const topicList = [
	'Pre-Algebra',
	'Algebra 1',
	'Algebra 2',
	'SAT Prep',
	'Experimental',
	'Geometry',
	'Trigonometry',
	'AP Review',
	'Pre-Calculus',
	'Calculus',
	'Statistics',
	'Indian Exams',
	'Community',
];
